name = "Vault Hunters 3rd Edition Jeefified"
author = "ArtificialDan"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d9840b9a261eb559ff7465090577dc81fde59189582dff963bdd0320410f7ff"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
