name = "Vault Hunters 3rd Edition Jeefified"
author = "ArtificialDan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f33e16de7f79b384055fb27b74d29e8d9087dafc0315aebc449a29e6ebb049ec"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
