name = "Vault Hunters 3rd Edition Jeefified"
author = "ArtificialDan"
version = "0.0.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d9db8be2d3114eb74bcf3173115c09da69797879f333de3284a1e9823d36cfd"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
